on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: AtimePkgtest

jobs:
  Atime-Pkg:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: SiyaoIsHiding/r-asymptotic-testing@v1
        with:
          alpha: '"0.1"'
